version: "3.9"

services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./docker/pg/Dockerfile
    environment:
      POSTGRES_USER: ioet_test
      POSTGRES_PASSWORD: uG7rI4hS4iR1cY1f
      POSTGRES_DB: payroll